version: '3'

services:
  nginx:
    container_name: nginx_ind
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www:z
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - yii
    depends_on:
      - php

  php:
    container_name: php_ind
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www:z
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:z
    networks:
      - yii
    user: root
    depends_on:
      - postgres

  postgres:
    container_name: post_ind
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: 'quiz'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - yii

networks:
  yii:
    driver: bridge
